-- GRIDHAND Billable Hour Hawk — Database Schema
-- Run this against your Supabase project to initialize the worker.

-- ─── Firm Connections ──────────────────────────────────────────────────────────
-- Stores OAuth tokens for Clio or API key for Rocket Matter per law firm client.

CREATE TABLE IF NOT EXISTS hawk_connections (
    id                       BIGSERIAL PRIMARY KEY,
    client_slug              TEXT        NOT NULL UNIQUE,
    -- Clio OAuth
    clio_access_token        TEXT,
    clio_refresh_token       TEXT,
    clio_expires_at          TIMESTAMPTZ,
    -- Rocket Matter API key auth
    rocketmatter_api_key     TEXT,
    -- Which system this firm uses
    active_system            TEXT        NOT NULL DEFAULT 'clio' CHECK (active_system IN ('clio', 'rocketmatter')),
    -- Contact numbers for SMS alerts
    billing_contact_phone    TEXT,          -- billing manager / billing paralegal
    managing_partner_phone   TEXT,          -- receives weekly summary
    firm_name                TEXT,
    -- Alert thresholds (configurable per firm)
    retainer_alert_threshold NUMERIC       DEFAULT 0.20,   -- alert when balance < 20% of retainer
    unbilled_flag_days       INT           DEFAULT 30,      -- flag time entries unbilled > 30 days
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─── Time Entries ──────────────────────────────────────────────────────────────
-- Mirror of time entries pulled from Clio / Rocket Matter.

CREATE TABLE IF NOT EXISTS time_entries (
    id                   BIGSERIAL PRIMARY KEY,
    client_slug          TEXT        NOT NULL REFERENCES hawk_connections(client_slug) ON DELETE CASCADE,
    external_entry_id    TEXT        NOT NULL,  -- Clio or RM entry ID
    attorney_name        TEXT,
    matter_id            TEXT,
    matter_name          TEXT,
    client_name          TEXT,
    activity_description TEXT,
    hours                NUMERIC(6,2),
    rate                 NUMERIC(8,2),
    amount               NUMERIC(10,2),
    entry_date           DATE,
    billed               BOOLEAN      NOT NULL DEFAULT FALSE,
    invoice_id           TEXT,
    flagged_unbilled     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE(client_slug, external_entry_id)
);

CREATE INDEX IF NOT EXISTS idx_time_entries_client_slug    ON time_entries(client_slug);
CREATE INDEX IF NOT EXISTS idx_time_entries_billed         ON time_entries(client_slug, billed);
CREATE INDEX IF NOT EXISTS idx_time_entries_flagged        ON time_entries(client_slug, flagged_unbilled);
CREATE INDEX IF NOT EXISTS idx_time_entries_attorney       ON time_entries(client_slug, attorney_name);
CREATE INDEX IF NOT EXISTS idx_time_entries_entry_date     ON time_entries(client_slug, entry_date);

-- ─── Invoice Drafts ────────────────────────────────────────────────────────────
-- Tracks invoice drafts auto-generated by the worker.

CREATE TABLE IF NOT EXISTS invoice_drafts (
    id                 BIGSERIAL PRIMARY KEY,
    client_slug        TEXT        NOT NULL REFERENCES hawk_connections(client_slug) ON DELETE CASCADE,
    matter_id          TEXT        NOT NULL,
    matter_name        TEXT,
    draft_external_id  TEXT,                -- ID in Clio/RM once created
    total_hours        NUMERIC(8,2),
    total_amount       NUMERIC(12,2),
    entry_count        INT,
    status             TEXT        NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'approved', 'rejected')),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invoice_drafts_client_slug ON invoice_drafts(client_slug);
CREATE INDEX IF NOT EXISTS idx_invoice_drafts_status      ON invoice_drafts(client_slug, status);

-- ─── Retainer Alerts ───────────────────────────────────────────────────────────
-- Log of every retainer low-balance alert sent.

CREATE TABLE IF NOT EXISTS retainer_alerts (
    id                BIGSERIAL PRIMARY KEY,
    client_slug       TEXT        NOT NULL REFERENCES hawk_connections(client_slug) ON DELETE CASCADE,
    matter_id         TEXT        NOT NULL,
    matter_name       TEXT,
    retainer_balance  NUMERIC(12,2),
    retainer_limit    NUMERIC(12,2),
    balance_pct       NUMERIC(5,2),
    alerted_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_retainer_alerts_client_slug ON retainer_alerts(client_slug);
CREATE INDEX IF NOT EXISTS idx_retainer_alerts_matter      ON retainer_alerts(client_slug, matter_id);

-- ─── Billing Alerts Log ────────────────────────────────────────────────────────
-- Full audit trail of every SMS sent by the worker.

CREATE TABLE IF NOT EXISTS billing_alerts (
    id           BIGSERIAL PRIMARY KEY,
    client_slug  TEXT        NOT NULL REFERENCES hawk_connections(client_slug) ON DELETE CASCADE,
    alert_type   TEXT        NOT NULL,   -- 'unbilled_flag'|'retainer_low'|'weekly_summary'|'attorney_reminder'|'invoice_draft'
    recipient    TEXT        NOT NULL,   -- phone number
    message_body TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_billing_alerts_client_slug ON billing_alerts(client_slug);
CREATE INDEX IF NOT EXISTS idx_billing_alerts_type        ON billing_alerts(client_slug, alert_type);

-- ─── Billing Snapshots ─────────────────────────────────────────────────────────
-- Daily/weekly billing performance snapshots for trend tracking.

CREATE TABLE IF NOT EXISTS billing_snapshots (
    id                   BIGSERIAL PRIMARY KEY,
    client_slug          TEXT        NOT NULL REFERENCES hawk_connections(client_slug) ON DELETE CASCADE,
    snapshot_date        DATE        NOT NULL,
    total_hours_logged   NUMERIC(8,2)  DEFAULT 0,
    hours_billed         NUMERIC(8,2)  DEFAULT 0,
    realization_rate     NUMERIC(5,2)  DEFAULT 0,   -- billed/logged as %
    total_billed         NUMERIC(12,2) DEFAULT 0,
    total_collected      NUMERIC(12,2) DEFAULT 0,
    outstanding          NUMERIC(12,2) DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(client_slug, snapshot_date)
);

CREATE INDEX IF NOT EXISTS idx_billing_snapshots_client_slug ON billing_snapshots(client_slug);
CREATE INDEX IF NOT EXISTS idx_billing_snapshots_date        ON billing_snapshots(client_slug, snapshot_date DESC);

-- ─── Helper: auto-update updated_at on time_entries ────────────────────────────

CREATE OR REPLACE FUNCTION hawk_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_time_entries_updated_at ON time_entries;
CREATE TRIGGER trg_time_entries_updated_at
    BEFORE UPDATE ON time_entries
    FOR EACH ROW EXECUTE FUNCTION hawk_set_updated_at();
